FROM scratch
ADD x86_64/29fbabd654554463f42d30cf1700017f3e97488965a15abe19a12517fc8d4609.tar.xz /
ADD x86_64/2a40e7877698f7121b37e4b0a51ce7dcfcfd2c578af7caed93864ef0488aa206.tar.xz /
ADD x86_64/3529dd20a8967a50d9738c026ca4262f03fffe47eb43f0d9bed6face6e7eded3.tar.xz /
ADD x86_64/37969beb2b368a6f0fbddf888371811d3ce4dfaf2da665a229fcf4ebc0427211.tar.xz /
ADD x86_64/4d281cf0846dcf5fd81ce73f51a3fc5836d4a0ad7be0fb69465624f73a4c35ab.tar.xz /
ADD x86_64/54ab60daa2c985749f09a06d4fe41ffcdcf030c54c8e1be4f903bac94ee50cde.tar.xz /

ENV LANG=en_US.UTF-8
ENV TZ=:/etc/localtime
ENV PATH=/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
ENV LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
ENV LAMBDA_TASK_ROOT=/var/task
ENV LAMBDA_RUNTIME_DIR=/var/runtime

WORKDIR /var/task

ENTRYPOINT ["/lambda-entrypoint.sh"]

# Start: MoveOn's custom additions
ENTRYPOINT ["/lambda-entrypoint.sh", "app.handler"]
EXPOSE 8000

# Install git and vim
RUN yum -y install git vim

# Install pyenv prerequisites
RUN yum groupinstall -y "Development Tools"
RUN yum install -y zlib zlib-devel bzip2-devel openssl-devel sqlite-devel libffi-devel gcc make patch bzip2 readline-devel sqlite tk-devel xz-devel

# Install pyenv
RUN curl https://pyenv.run | bash
RUN echo -e '\n# Load pyenv and pyenv-virtualenv automatically\nexport PYENV_ROOT="$HOME/.pyenv"\ncommand -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"\neval "$(pyenv init -)"\neval "$(pyenv virtualenv-init -)"' >> ~/.bashrc

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install
RUN rm awscliv2.zip
RUN rm -r aws
# End: MoveOn's custom additions
